spring.application.name=safari-tms
spring.datasource.url=jdbc:sqlserver://DESKTOP-BPF7P7K\\SQLEXPRESS:1433;databaseName=safari_tms;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect