import { useState } from 'react';
import { notificationApi } from '../../api/api';
import { useApi } from '../../hooks/useApi';
import DataTable from '../../components/DataTable';
import StatusBadge from '../../components/StatusBadge';
import { Card, ErrorState, Select, SkeletonTable, dateTimeFmt, titleCase } from '../../components/ui';

export default function NotificationLogPage() {
  const notifications = useApi(() => notificationApi.list(), []);
  const [channel, setChannel] = useState('');

  const all = notifications.data ?? [];
  const rows = all.filter((n) => !channel || n.channel === channel);

  const columns = [
    {
      key: 'createdAt',
      header: 'Sent',
      width: 158,
      render: (r) => dateTimeFmt(r.sentAt ?? r.createdAt),
    },
    {
      key: 'channel',
      header: 'Channel',
      width: 96,
      render: (r) => <span className="badge badge-neutral">{r.channel}</span>,
    },
    {
      key: 'recipientName',
      header: 'Recipient',
      width: 180,
      render: (r) => (
        <div>
          <div>{r.recipientName}</div>
          <div className="tiny muted truncate">{r.recipientAddress}</div>
        </div>
      ),
    },
    {
      key: 'subject',
      header: 'Message',
      render: (r) => (
        <div>
          {r.subject && <div className="strong small">{r.subject}</div>}
          <div className="tiny muted truncate" style={{ maxWidth: 420 }}>
            {r.body}
          </div>
        </div>
      ),
    },
    {
      key: 'relatedEntity',
      header: 'Context',
      width: 128,
      render: (r) =>
        r.relatedEntity ? (
          <span className="tiny">
            {r.relatedEntity} #{r.relatedId}
          </span>
        ) : (
          <span className="muted">—</span>
        ),
    },
    {
      key: 'status',
      header: 'Status',
      width: 110,
      render: (r) => (
        <StatusBadge value={r.status === 'SENT' ? 'SUCCESS' : r.status} label={titleCase(r.status)} />
      ),
    },
  ];

  return (
    <div className="page">
      <div className="page-head">
        <div>
          <div className="eyebrow">Communications</div>
          <h1>Notification log</h1>
          <p className="lede">
            Every email and SMS the system generated. Delivery is simulated — no external provider is
            wired in — but each message is recorded exactly as it would have been sent.
          </p>
        </div>
      </div>

      <div className="grid grid-3 mb-3">
        <Card className="kpi">
          <div className="kpi-label">Total messages</div>
          <div className="kpi-value">{all.length}</div>
        </Card>
        <Card className="kpi kpi-amber">
          <div className="kpi-label">Email</div>
          <div className="kpi-value">{all.filter((n) => n.channel === 'EMAIL').length}</div>
        </Card>
        <Card className="kpi kpi-terracotta">
          <div className="kpi-label">SMS</div>
          <div className="kpi-value">{all.filter((n) => n.channel === 'SMS').length}</div>
        </Card>
      </div>

      {notifications.loading ? (
        <SkeletonTable rows={7} cols={6} />
      ) : notifications.error ? (
        <ErrorState message={notifications.error} onRetry={notifications.reload} />
      ) : (
        <DataTable
          columns={columns}
          rows={rows}
          initialSort={{ key: 'createdAt', dir: 'desc' }}
          searchPlaceholder="Search recipient, subject or body…"
          emptyIcon="🔔"
          emptyTitle="No notifications yet"
          emptyMessage="Messages generated by bookings, payments and cases will appear here."
          filters={
            <Select
              value={channel}
              onChange={(e) => setChannel(e.target.value)}
              style={{ width: 150 }}
              aria-label="Filter by channel"
            >
              <option value="">All channels</option>
              <option value="EMAIL">Email</option>
              <option value="SMS">SMS</option>
            </Select>
          }
        />
      )}
    </div>
  );
}
